/* exported data */

let data = {
  view: 'home-page',
  currencies: [],
  logos: [
    {
      id: 1,
      name: 'Bitcoin',
      symbol: 'BTC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1.png',
    },
    {
      id: 1027,
      name: 'Ethereum',
      symbol: 'ETH',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
    },
    {
      id: 825,
      name: 'Tether USDt',
      symbol: 'USDT',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/825.png',
    },
    {
      id: 1839,
      name: 'BNB',
      symbol: 'BNB',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png',
    },
    {
      id: 52,
      name: 'XRP',
      symbol: 'XRP',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/52.png',
    },
    {
      id: 5426,
      name: 'Solana',
      symbol: 'SOL',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
    },
    {
      id: 3408,
      name: 'USDC',
      symbol: 'USDC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png',
    },
    {
      id: 2010,
      name: 'Cardano',
      symbol: 'ADA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2010.png',
    },
    {
      id: 74,
      name: 'Dogecoin',
      symbol: 'DOGE',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/74.png',
    },
    {
      id: 1958,
      name: 'TRON',
      symbol: 'TRX',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png',
    },
    {
      id: 1975,
      name: 'Chainlink',
      symbol: 'LINK',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1975.png',
    },
    {
      id: 11419,
      name: 'Toncoin',
      symbol: 'TON',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11419.png',
    },
    {
      id: 5805,
      name: 'Avalanche',
      symbol: 'AVAX',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png',
    },
    {
      id: 3890,
      name: 'Polygon',
      symbol: 'MATIC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png',
    },
    {
      id: 6636,
      name: 'Polkadot',
      symbol: 'DOT',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6636.png',
    },
    {
      id: 4943,
      name: 'Dai',
      symbol: 'DAI',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png',
    },
    {
      id: 2,
      name: 'Litecoin',
      symbol: 'LTC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2.png',
    },
    {
      id: 5994,
      name: 'Shiba Inu',
      symbol: 'SHIB',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5994.png',
    },
    {
      id: 1831,
      name: 'Bitcoin Cash',
      symbol: 'BCH',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1831.png',
    },
    {
      id: 3957,
      name: 'UNUS SED LEO',
      symbol: 'LEO',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3957.png',
    },
    {
      id: 3794,
      name: 'Cosmos',
      symbol: 'ATOM',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3794.png',
    },
    {
      id: 7083,
      name: 'Uniswap',
      symbol: 'UNI',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png',
    },
    {
      id: 3897,
      name: 'OKB',
      symbol: 'OKB',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3897.png',
    },
    {
      id: 512,
      name: 'Stellar',
      symbol: 'XLM',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/512.png',
    },
    {
      id: 328,
      name: 'Monero',
      symbol: 'XMR',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/328.png',
    },
    {
      id: 20396,
      name: 'Kaspa',
      symbol: 'KAS',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/20396.png',
    },
    {
      id: 2563,
      name: 'TrueUSD',
      symbol: 'TUSD',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2563.png',
    },
    {
      id: 1321,
      name: 'Ethereum Classic',
      symbol: 'ETC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1321.png',
    },
    {
      id: 4157,
      name: 'THORChain',
      symbol: 'RUNE',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4157.png',
    },
    {
      id: 3635,
      name: 'Cronos',
      symbol: 'CRO',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png',
    },
    {
      id: 2280,
      name: 'Filecoin',
      symbol: 'FIL',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2280.png',
    },
    {
      id: 8916,
      name: 'Internet Computer',
      symbol: 'ICP',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8916.png',
    },
    {
      id: 8000,
      name: 'Lido DAO',
      symbol: 'LDO',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8000.png',
    },
    {
      id: 4642,
      name: 'Hedera',
      symbol: 'HBAR',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4642.png',
    },
    {
      id: 21794,
      name: 'Aptos',
      symbol: 'APT',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/21794.png',
    },
    {
      id: 6535,
      name: 'NEAR Protocol',
      symbol: 'NEAR',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6535.png',
    },
    {
      id: 10603,
      name: 'Immutable',
      symbol: 'IMX',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/10603.png',
    },
    {
      id: 27075,
      name: 'Mantle',
      symbol: 'MNT',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/27075.png',
    },
    {
      id: 3077,
      name: 'VeChain',
      symbol: 'VET',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3077.png',
    },
    {
      id: 4687,
      name: 'BUSD',
      symbol: 'BUSD',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4687.png',
    },
    {
      id: 11840,
      name: 'Optimism',
      symbol: 'OP',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png',
    },
    {
      id: 7226,
      name: 'Injective',
      symbol: 'INJ',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7226.png',
    },
    {
      id: 7278,
      name: 'Aave',
      symbol: 'AAVE',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7278.png',
    },
    {
      id: 6719,
      name: 'The Graph',
      symbol: 'GRT',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6719.png',
    },
    {
      id: 1518,
      name: 'Maker',
      symbol: 'MKR',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1518.png',
    },
    {
      id: 11841,
      name: 'Arbitrum',
      symbol: 'ARB',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11841.png',
    },
    {
      id: 4195,
      name: 'FTX Token',
      symbol: 'FTT',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4195.png',
    },
    {
      id: 5690,
      name: 'Render',
      symbol: 'RNDR',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5690.png',
    },
    {
      id: 22861,
      name: 'Celestia',
      symbol: 'TIA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/22861.png',
    },
    {
      id: 3155,
      name: 'Quant',
      symbol: 'QNT',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3155.png',
    },
    {
      id: 6892,
      name: 'MultiversX',
      symbol: 'EGLD',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6892.png',
    },
    {
      id: 4030,
      name: 'Algorand',
      symbol: 'ALGO',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4030.png',
    },
    {
      id: 2416,
      name: 'Theta Network',
      symbol: 'THETA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2416.png',
    },
    {
      id: 4847,
      name: 'Stacks',
      symbol: 'STX',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4847.png',
    },
    {
      id: 2586,
      name: 'Synthetix',
      symbol: 'SNX',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2586.png',
    },
    {
      id: 4558,
      name: 'Flow',
      symbol: 'FLOW',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4558.png',
    },
    {
      id: 26081,
      name: 'First Digital USD',
      symbol: 'FDUSD',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/26081.png',
    },
    {
      id: 1720,
      name: 'IOTA',
      symbol: 'IOTA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1720.png',
    },
    {
      id: 3602,
      name: 'Bitcoin SV',
      symbol: 'BSV',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3602.png',
    },
    {
      id: 3513,
      name: 'Fantom',
      symbol: 'FTM',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3513.png',
    },
    {
      id: 6210,
      name: 'The Sandbox',
      symbol: 'SAND',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6210.png',
    },
    {
      id: 6783,
      name: 'Axie Infinity',
      symbol: 'AXS',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6783.png',
    },
    {
      id: 4172,
      name: 'Terra Classic',
      symbol: 'LUNC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4172.png',
    },
    {
      id: 1966,
      name: 'Decentraland',
      symbol: 'MANA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1966.png',
    },
    {
      id: 2011,
      name: 'Tezos',
      symbol: 'XTZ',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2011.png',
    },
    {
      id: 1376,
      name: 'Neo',
      symbol: 'NEO',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1376.png',
    },
    {
      id: 4846,
      name: 'Kava',
      symbol: 'KAVA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4846.png',
    },
    {
      id: 2087,
      name: 'KuCoin Token',
      symbol: 'KCS',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2087.png',
    },
    {
      id: 1765,
      name: 'EOS',
      symbol: 'EOS',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1765.png',
    },
    {
      id: 8646,
      name: 'Mina',
      symbol: 'MINA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8646.png',
    },
    {
      id: 19891,
      name: 'USDD',
      symbol: 'USDD',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/19891.png',
    },
    {
      id: 11092,
      name: 'Bitget Token',
      symbol: 'BGB',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11092.png',
    },
    {
      id: 7080,
      name: 'Gala',
      symbol: 'GALA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7080.png',
    },
    {
      id: 2634,
      name: 'XDC Network',
      symbol: 'XDC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2634.png',
    },
    {
      id: 20947,
      name: 'Sui',
      symbol: 'SUI',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/20947.png',
    },
    {
      id: 4256,
      name: 'Klaytn',
      symbol: 'KLAY',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4256.png',
    },
    {
      id: 25028,
      name: 'ORDI',
      symbol: 'ORDI',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/25028.png',
    },
    {
      id: 23121,
      name: 'Blur',
      symbol: 'BLUR',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/23121.png',
    },
    {
      id: 11156,
      name: 'dYdX (ethDYDX)',
      symbol: 'ETHDYDX',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11156.png',
    },
    {
      id: 18876,
      name: 'ApeCoin',
      symbol: 'APE',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/18876.png',
    },
    {
      id: 6953,
      name: 'Frax Share',
      symbol: 'FXS',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6953.png',
    },
    {
      id: 10791,
      name: 'eCash',
      symbol: 'XEC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/10791.png',
    },
    {
      id: 23149,
      name: 'Sei',
      symbol: 'SEI',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/23149.png',
    },
    {
      id: 4066,
      name: 'Chiliz',
      symbol: 'CHZ',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4066.png',
    },
    {
      id: 7653,
      name: 'Oasis Network',
      symbol: 'ROSE',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7653.png',
    },
    {
      id: 7334,
      name: 'Conflux',
      symbol: 'CFX',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7334.png',
    },
    {
      id: 2943,
      name: 'Rocket Pool',
      symbol: 'RPL',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2943.png',
    },
    {
      id: 6538,
      name: 'Curve DAO Token',
      symbol: 'CRV',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6538.png',
    },
    {
      id: 5632,
      name: 'Arweave',
      symbol: 'AR',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5632.png',
    },
    {
      id: 7186,
      name: 'PancakeSwap',
      symbol: 'CAKE',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7186.png',
    },
    {
      id: 1785,
      name: 'Gas',
      symbol: 'GAS',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1785.png',
    },
    {
      id: 1659,
      name: 'Gnosis',
      symbol: 'GNO',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1659.png',
    },
    {
      id: 1437,
      name: 'Zcash',
      symbol: 'ZEC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1437.png',
    },
    {
      id: 5176,
      name: 'Tether Gold',
      symbol: 'XAUt',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5176.png',
    },
    {
      id: 5964,
      name: 'Trust Wallet Token',
      symbol: 'TWT',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5964.png',
    },
    {
      id: 7129,
      name: 'TerraClassicUSD',
      symbol: 'USTC',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7129.png',
    },
    {
      id: 20314,
      name: 'Terra',
      symbol: 'LUNA',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/20314.png',
    },
    {
      id: 28298,
      name: 'Beam',
      symbol: 'BEAM',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/28298.png',
    },
    {
      id: 24478,
      name: 'Pepe',
      symbol: 'PEPE',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/24478.png',
    },
    {
      id: 11857,
      name: 'GMX',
      symbol: 'GMX',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11857.png',
    },
  ],
  favorites: [],
};

window.addEventListener('beforeunload', function (event) {
  const assetsJSON = JSON.stringify(data);
  localStorage.setItem('javascript-local-storage', assetsJSON);
});

const previousAssetsJSON = localStorage.getItem('javascript-local-storage');
if (previousAssetsJSON !== null) {
  data = JSON.parse(previousAssetsJSON);
}
